//exports demo data for the app

export const demoData = [
    {
        id: 1,
        title: "First Item",
        description: "This is the first item",
        location: "",
        lastTrans: "2023-3-28",
        lastTransTime: "12:00",
        lastTransAmount: 300,
        phone: "01700000000",
        transection: [
            {
                id: 1,
                title: "First Item",
                description: "This is the first item",
                amount: 100,
                //date is in the format of YYYY-MM-DD
                date: "2023-3-28",
                time: "12:00",
                type: "income",
            },
            {
                id: 2,
                title: "Second Item",
                description: "This is the second item",
                amount: -200,
                date: "2020-10-10",
                time: "12:00",
                type: "expense",
            },
            {
                id: 3,
                title: "Third Item",
                description: "This is the third item",
                amount: 300,
                date: "2020-10-10",
                time: "12:00",
                type: "income",
            },
        ],
    },
    {
        id: 2,
        title: "Second Item",
        description: "This is the second item",
        location: "",
        lastTrans: "2023-3-28",
        lastTransTime: "12:00",
        lastTransAmount: -300,
        phone: "01700000000",
        transection: [
            {
                id: 1,
                title: "First Item",
                description: "This is the first item",
                amount: 100,
                date: "2023-3-28",
                time: "12:00",
                type: "income",
            },
        ],
    },
    {
        id: 3,
        title: "Third Item",
        description: "This is the third item",
        location: "",
        lastTrans: "2023-3-28",
        lastTransTime: "12:00",
        lastTransAmount: 300,
        phone: "01700000000",
        transection: [
            {
                id: 1,
                title: "First Item",
                description: "This is the first item",
                amount: 100,
                date: "2023-3-28",
                time: "12:00",
                type: "income",
            },
            {
                id: 2,
                title: "Second Item",
                description: "This is the second item",
                amount: 200,
                date: "2020-10-10",
                time: "12:00",
                type: "expense",
            },
            {
                id: 3,
                title: "Third Item",
                description: "This is the third item",
                amount: 300,
                date: "2020-10-10",
                time: "12:00",
                type: "income",
            },
        ],
    },
    {
        id: 4,
        title: "Fourth Item",
        description: "This is the fourth item",
        location: "",
        lastTrans: "2023-3-28",
        lastTransTime: "12:00",
        lastTransAmount: -300,
        phone: "01700000000",
        transection: [
            {
                id: 1,
                title: "First Item",
                description: "This is the first item",
                amount: 100,
                date: "2023-3-28",
                time: "12:00",
                type: "income",
            },
            {
                id: 2,
                title: "Second Item",
                description: "This is the second item",
                amount: 200,
                date: "2020-10-10",
                time: "12:00",
                type: "expense",
            },
            {
                id: 3,
                title: "Third Item",
                description: "This is the third item",
                amount: 300,
                date: "2020-10-10",
                time: "12:00",
                type: "income",
            },
        ],
    },
    {
        id: 5,
        title: "Fifth Item",
        description: "This is the fifth item",
        location: "",
        lastTrans: "2023-3-28",
        lastTransTime: "12:00",
        lastTransAmount: 300,
        phone: "01700000000",
        transection: [
            {
                id: 1,
                title: "First Item",
                description: "This is the first item",
                amount: 100,
                date: "2023-3-28",
                time: "12:00",
                type: "income",
            },
            {
                id: 2,
                title: "Second Item",
                description: "This is the second item",
                amount: 200,
                date: "2020-10-10",
                time: "12:00",
                type: "expense",
            },
            {
                id: 3,
                title: "Third Item",
                description: "This is the third item",
                amount: 300,
                date: "2020-10-10",
                time: "12:00",
                type: "income",
            },
        ],
    },
    {
        id: 6,
        title: "Sixth Item",
        description: "This is the sixth item",
        location: "",
        lastTrans: "2023-3-28",
        lastTransTime: "12:00",
        lastTransAmount: 300,
        phone: "01700000000",
        transection: [
            {
                id: 1,
                title: "First Item",
                description: "This is the first item",
                amount: 100,
                date: "2023-3-28",
                time: "12:00",
                type: "income",
            },
            {
                id: 2,
                title: "Second Item",
                description: "This is the second item",
                amount: 200,
                date: "2020-10-10",
                time: "12:00",
                type: "expense",
            },
            {
                id: 3,
                title: "Third Item",
                description: "This is the third item",
                amount: 300,
                date: "2020-10-10",
                time: "12:00",
                type: "income",
            },
        ],
    },
    {
        id: 7,
        title: "Seventh Item",
        description: "This is the seventh item",
        location: "",
        lastTrans: "2023-3-28",
        lastTransTime: "12:00",
        lastTransAmount: 300,
        phone: "01700000000",
        transection: [
            {
                id: 1,
                title: "First Item",
                description: "This is the first item",
                amount: 100,
                date: "2023-3-28",
                time: "12:00",
                type: "income",
            },
            {
                id: 2,
                title: "Second Item",
                description: "This is the second item",
                amount: 200,
                date: "2020-10-10",
                time: "12:00",
                type: "expense",
            },
            {
                id: 3,
                title: "Third Item",
                description: "This is the third item",
                amount: 300,
                date: "2020-10-10",
                time: "12:00",
                type: "income",
            },
        ],
    },
    {
        id: 8,
        title: "Eighth Item",
        description: "This is the eighth item",
        location: "",
        lastTrans: "2023-3-28",
        lastTransTime: "12:00",
        lastTransAmount: 300,
        phone: "01700000000",
        transection: [
            {
                id: 1,
                title: "First Item",
                description: "This is the first item",
                amount: 100,
                date: "2023-3-28",
                time: "12:00",
                type: "income",
            },
            {
                id: 2,
                title: "Second Item",
                description: "This is the second item",
                amount: 200,
                date: "2020-10-10",
                time: "12:00",
                type: "expense",
            },
            {
                id: 3,
                title: "Third Item",
                description: "This is the third item",
                amount: 300,
                date: "2020-10-10",
                time: "12:00",
                type: "income",
            },
        ],
    },
    {
        id: 9,
        title: "Ninth Item",
        description: "This is the ninth item",
        location: "",
        lastTrans: "2023-3-28",
        lastTransTime: "12:00",
        lastTransAmount: 300,
        phone: "01700000000",
        transection: [
            {
                id: 1,
                title: "First Item",
                description: "This is the first item",
                amount: 100,
                date: "2023-3-28",
                time: "12:00",
                type: "income",
            },
            {
                id: 2,
                title: "Second Item",
                description: "This is the second item",
                amount: 200,
                date: "2020-10-10",
                time: "12:00",
                type: "expense",
            },
            {
                id: 3,
                title: "Third Item",
                description: "This is the third item",
                amount: 300,
                date: "2020-10-10",
                time: "12:00",
                type: "income",
            },
        ],
    },
    {
        id: 10,
        title: "Tenth Item",
        description: "This is the tenth item",
        location: "",
        lastTrans: "2023-3-28",
        lastTransTime: "12:00",
        lastTransAmount: 300,
        phone: "01700000000",
        transection: [
            {
                id: 1,
                title: "First Item",
                description: "This is the first item",
                amount: 100,
                date: "2023-3-28",
                time: "12:00",
                type: "income",
            },
            {
                id: 2,
                title: "Second Item",
                description: "This is the second item",
                amount: 200,
                date: "2020-10-10",
                time: "12:00",
                type: "expense",
            },
            {
                id: 3,
                title: "Third Item",
                description: "This is the third item",
                amount: 300,
                date: "2020-10-10",
                time: "12:00",
                type: "income",
            },
        ],
    },
    {
        id: 11,
        title: "Eleventh Item",
        description: "This is the eleventh item",
        location: "",
        lastTrans: "2023-3-28",
        lastTransTime: "12:00",
        lastTransAmount: 300,
        phone: "01700000000",
        transection: [
            {
                id: 1,
                title: "First Item",
                description: "This is the first item",
                amount: 100,
                date: "2023-3-28",
                time: "12:00",
                type: "income",
            },
            {
                id: 2,
                title: "Second Item",
                description: "This is the second item",
                amount: 200,
                date: "2020-10-10",
                time: "12:00",
                type: "expense",
            },
            {
                id: 3,
                title: "Third Item",
                description: "This is the third item",
                amount: 300,
                date: "2020-10-10",
                time: "12:00",
                type: "income",
            },
        ],
    },
];
